# Generated by Django 4.2.9 on 2024-02-04 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("taivin_cms", "0002_presentations_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="banners",
            options={"verbose_name": "Баннер", "verbose_name_plural": "Баннеры"},
        ),
        migrations.AlterModelOptions(
            name="previews",
            options={"verbose_name": "Превью", "verbose_name_plural": "Превью"},
        ),
        migrations.AddField(
            model_name="previews",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="taivin_cms.customers",
            ),
        ),
        migrations.AddField(
            model_name="previews",
            name="name",
            field=models.CharField(
                default=1, max_length=255, verbose_name="Название превью"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="previews",
            name="preview",
            field=models.ImageField(
                blank=True, null=True, upload_to="preview/", verbose_name="Превью"
            ),
        ),
        migrations.AddField(
            model_name="previews",
            name="slug_name",
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="customers",
            name="link",
            field=models.CharField(max_length=500, verbose_name="Ссылка на заказчика"),
        ),
        migrations.AlterField(
            model_name="customers",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Имя заказчика"),
        ),
        migrations.AlterField(
            model_name="presentations",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="taivin_cms.customers",
            ),
        ),
        migrations.AlterField(
            model_name="presentations",
            name="main_banner",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="presentations/",
                verbose_name="Главный баннер",
            ),
        ),
        migrations.AlterField(
            model_name="presentations",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Название презентации"),
        ),
    ]
