# Generated by Django 4.2.9 on 2024-02-04 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("taivin_cms", "0003_alter_banners_options_alter_previews_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="banners",
            name="banner",
            field=models.ImageField(
                blank=True, null=True, upload_to="banners/", verbose_name="Баннер"
            ),
        ),
        migrations.AddField(
            model_name="banners",
            name="banner_type",
            field=models.IntegerField(
                choices=[(1, "Горизонтальный"), (2, "Вертикальный"), (3, "Квадратный")],
                default=1,
                verbose_name="Вид баннера",
            ),
        ),
        migrations.AddField(
            model_name="banners",
            name="color",
            field=models.CharField(
                default=1, max_length=255, verbose_name="Цвет подцветки"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="banners",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="taivin_cms.customers",
            ),
        ),
        migrations.AddField(
            model_name="banners",
            name="name",
            field=models.CharField(
                default=1, max_length=255, verbose_name="Название превью"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="banners",
            name="position",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Порядок сортировки"
            ),
        ),
        migrations.AddField(
            model_name="banners",
            name="slug_name",
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="presentations",
            name="position",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Порядок сортировки"
            ),
        ),
        migrations.AddField(
            model_name="previews",
            name="color",
            field=models.CharField(
                default=1, max_length=255, verbose_name="Цвет подцветки"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="previews",
            name="position",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Порядок сортировки"
            ),
        ),
        migrations.AddField(
            model_name="slides",
            name="position",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Порядок сортировки"
            ),
        ),
    ]
