# Generated by Django 4.2.9 on 2024-02-04 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "taivin_cms",
            "0004_banners_banner_banners_banner_type_banners_color_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="banners",
            name="color",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Цвет подцветки"
            ),
        ),
        migrations.AlterField(
            model_name="previews",
            name="color",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Цвет подцветки"
            ),
        ),
    ]
