# Generated by Django 4.2.9 on 2024-02-10 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("taivin_cms", "0005_alter_banners_color_alter_previews_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="Arts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название Арта"),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True, null=True, upload_to="arts/", verbose_name="Арты"
                    ),
                ),
                ("slug_name", models.SlugField(unique=True)),
                (
                    "position",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Порядок сортировки"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Цвет подцветки",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="taivin_cms.customers",
                    ),
                ),
            ],
            options={
                "verbose_name": "Арт",
                "verbose_name_plural": "Арты",
            },
        ),
    ]
