# Generated by Django 4.2.9 on 2024-02-10 12:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("taivin_cms", "0006_arts"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="creatives",
            options={"verbose_name": "Креатив", "verbose_name_plural": "Креативы"},
        ),
        migrations.AddField(
            model_name="creatives",
            name="color",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Цвет подцветки"
            ),
        ),
        migrations.AddField(
            model_name="creatives",
            name="creative",
            field=models.ImageField(
                blank=True, null=True, upload_to="creatives/", verbose_name="Креатив"
            ),
        ),
        migrations.AddField(
            model_name="creatives",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="taivin_cms.customers",
            ),
        ),
        migrations.AddField(
            model_name="creatives",
            name="name",
            field=models.CharField(
                default=None, max_length=255, verbose_name="Название Креатива"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="creatives",
            name="position",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Порядок сортировки"
            ),
        ),
        migrations.AddField(
            model_name="creatives",
            name="slug_name",
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
