# Generated by Django 4.2.9 on 2024-02-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taivin_cms", "0007_alter_creatives_options_creatives_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="presentations",
            name="main_bg_color",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Цвет на главном экране",
            ),
        ),
    ]
