# Generated by Django 4.2.9 on 2024-02-17 20:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taivin_cms.models


class Migration(migrations.Migration):
    dependencies = [
        ("taivin_cms", "0008_presentations_main_bg_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "linear_gradient",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="Линейный градиент",
                    ),
                ),
                ("code", models.CharField(max_length=255, verbose_name="Код цвета")),
            ],
            options={
                "verbose_name": "Цвет",
                "verbose_name_plural": "Цвета",
            },
        ),
        migrations.DeleteModel(
            name="Colors",
        ),
        migrations.AlterModelOptions(
            name="articles",
            options={"verbose_name": "Абзац", "verbose_name_plural": "Абзац"},
        ),
        migrations.AlterModelOptions(
            name="fonts",
            options={"verbose_name": "Шрифт", "verbose_name_plural": "Шрифты"},
        ),
        migrations.AddField(
            model_name="articles",
            name="header",
            field=models.TextField(
                blank=True, null=True, verbose_name="Заголовок абзаца"
            ),
        ),
        migrations.AddField(
            model_name="articles",
            name="position",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Порядок сортировки"
            ),
        ),
        migrations.AddField(
            model_name="articles",
            name="presentation",
            field=models.ForeignKey(
                blank=True,
                help_text="Презентация",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="taivin_cms.presentations",
                verbose_name="Презентация",
            ),
        ),
        migrations.AddField(
            model_name="articles",
            name="text",
            field=models.TextField(blank=True, null=True, verbose_name="Текст абзаца"),
        ),
        migrations.AddField(
            model_name="fonts",
            name="file_format",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "otf"), (2, "ttf"), (3, "woff")],
                default=1,
                verbose_name="Формат файла со шрифтами",
            ),
        ),
        migrations.AddField(
            model_name="fonts",
            name="font_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=taivin_cms.models.get_upload_fonts_path,
                verbose_name="Шрифт файла",
            ),
        ),
        migrations.AddField(
            model_name="fonts",
            name="name",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=255,
                verbose_name="Название цвета",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fonts",
            name="presentation",
            field=models.ForeignKey(
                blank=True,
                help_text="Презентация",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="taivin_cms.presentations",
                verbose_name="Презентация",
            ),
        ),
        migrations.AddField(
            model_name="slides",
            name="presentation",
            field=models.ForeignKey(
                blank=True,
                help_text="Презентация",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="taivin_cms.presentations",
                verbose_name="Презентация",
            ),
        ),
        migrations.AddField(
            model_name="slides",
            name="slide_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="slides", verbose_name="Слайд"
            ),
        ),
    ]
