# Generated by Django 4.2.9 on 2024-02-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taivin_cms", "0010_color_presentation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slides",
            name="chapter",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Раздел"
            ),
        ),
        migrations.AlterField(
            model_name="slides",
            name="size",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Размер"
            ),
        ),
    ]
