# Generated by Django 4.2.9 on 2024-02-17 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taivin_cms", "0012_presentations_about_customer_additionalbenefits"),
    ]

    operations = [
        migrations.AddField(
            model_name="color",
            name="position",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Порядок сортировки"
            ),
        ),
        migrations.AddField(
            model_name="fonts",
            name="position",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Порядок сортировки"
            ),
        ),
    ]
