# Generated by Django 4.2.9 on 2024-02-17 21:15

from django.db import migrations, models
import taivin_cms.models


class Migration(migrations.Migration):
    dependencies = [
        ("taivin_cms", "0013_color_position_fonts_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slides",
            name="slide_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=taivin_cms.models.get_upload_slides_path,
                verbose_name="Слайд",
            ),
        ),
    ]
