# Generated by Django 4.2.9 on 2024-02-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("taivin_cms", "0014_alter_slides_slide_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="articles",
            name="counter_color",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Код цвета счетчика"
            ),
        ),
        migrations.AddField(
            model_name="presentations",
            name="font_color_background",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Градиент background блока со шрифтами и цветами",
            ),
        ),
    ]
