# Generated by Django 4.2.9 on 2024-02-22 08:48

from django.db import migrations, models
import taivin_cms.models


class Migration(migrations.Migration):
    dependencies = [
        ("taivin_cms", "0016_color_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="fonts",
            name="description_font_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=taivin_cms.models.get_upload_fonts_path,
                verbose_name="Шрифт описания",
            ),
        ),
    ]
